<?php
/**
 * Copyright © Webscale. All rights reserved.
 * See LICENSE for license details.
 */

/** @var \Webscale\Varnish\Block\System\Cache\Additional $block */
?>

<?php if ($block->isEnabled()): ?>
<form id="purge_all_form" name="purge_all_form" method="post"
      action="<?= /* @noEscape */ $block->getPurgeAllUrl() ?>">
    <input type="hidden" name="form_key" value="<?= /* @noEscape */ $block->getFormKey() ?>" />
    <div class="additional-cache-management">
        <p>
            <button type="submit" class="scalable">
                <?= /* @noEscape */ __('Flush VelocityEDGE Cache') ?>
            </button>
            <span><?= /* @noEscape */ __('Webscale VelocityEDGE cache.') ?></span>
        </p>
    </div>
</form>
<form id="purge_by_url_form" name="purge_by_url_form" method="post"
      action="<?= /* @noEscape */ $block->getPurgeByUrl() ?>">
    <input type="hidden" name="form_key" value="<?= /* @noEscape */ $block->getFormKey() ?>" />
    <div class="additional-cache-management">
        <p>
            <textarea cols="50" rows="4" class="input-text admin__control-textarea" type="textarea" name="purge_url" id="purge_url" placeholder="http://domain.com/index.html
 *.example.com/path/*/home
 /
 /*" ></textarea>
        </p>
        <p>
            <button type="submit" class="scalable">
                <?= /* @noEscape */ __('Purge VelocityEDGE Cache by URL') ?>
            </button>
            <span><?= /* @noEscape */ __('Purge a specific URL from the Webscale VelocityEDGE cache.') ?></span>
        </p>

</form>
<?php endif; ?>
